### ISSUE TITLE
npm audit warnings + errors

### ISSUE THREAD

**Issue by strarsis** [dfernandez79/ase-util#3]
@dfernandez79:
I get `npm audit` warnings + errors in a [project](https://github.com/strarsis/ase-scss) that uses your (awesome) `ase-util` library.

PR with updated packages: https://github.com/dfernandez79/ase-util/pull/2
Please also release to npm after merging so I can update the dependency in the project.

**Comment by dfernandez79** [comment]
Thank you so much for the update... I just published `1.0.2` to NPM, that should fix the audit warning.
